<?php

/**
 * @file
 * Main module file.
 */

define('DATABASE_ANALYSER_DEFAULT_SEARCH_QUERY', 'http://');
define('DATABASE_ANALYSER_DEFAULT_REPLACE_QUERY', 'https://');

/**
 * Implements hook_menu().
 */
function database_analyser_menu() {
  return array(
    'admin/config/development/database-analyser' => array(
      'title' => 'Database analyser',
      'description' => 'Analyse all database tables for a search query.',
      'access arguments' => array('access database analyser'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_database_analyser_get_page'),
    ),
    'admin/config/development/database-analyser/%' => array(
      'title' => 'Database analyser',
      'description' => 'Analyse all database tables for a search query.',
      'access arguments' => array('access database analyser'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_database_analyser_get_page', 4),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function database_analyser_permission() {
  return array(
    'access database analyser' => array(
      'title' => t('Access database analyser'),
      'description' => t('Access the database analyser inspection page.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Get the page.
 */
function _database_analyser_get_page($form, &$form_state, $table) {

  // Add the js.
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');

  // Initialize the search string.
  $search_string = DATABASE_ANALYSER_DEFAULT_SEARCH_QUERY;
  $replace_string = DATABASE_ANALYSER_DEFAULT_REPLACE_QUERY;

  // Update based on the form state.
  if (!empty($form_state['input']['search'])) {
    $search_string = $form_state['input']['search'];
  }
  if (!empty($form_state['input']['replace'])) {
    $replace_string = $form_state['input']['replace'];
  }

  // Input fieldset.
  $form['input'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['input']['search'] = array(
    '#type' => 'textfield',
    '#title' => t('Search string'),
    '#default_value' => $search_string,
  );

  $form['input']['replace'] = array(
    '#type' => 'textfield',
    '#title' => t('Replace string'),
    '#default_value' => $replace_string,
  );

  // Add the search submit button.
  $form['input']['find'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('_database_analyser_submit_search'),
  );

  // Get the entries.
  $entries = _database_analyser_create_entries_table($search_string, $table);

  // Output fieldset.
  $form['output'] = array(
    '#type' => 'fieldset',
    '#title' => t('Output'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  // Check for entries.
  if (!empty($entries)) {

    foreach ($entries as $entry) {

      // Add the fieldset.
      $form['output'][$entry['table_name']] = array(
        '#type' => 'fieldset',
        '#title' => $entry['table_name'] . ' ' . '(' . $entry['count'] . ')',
        '#collapsible' => TRUE,
        '#collapsed' => !empty($table) ? FALSE : TRUE,
      );

      // Add the button
      $form['output'][$entry['table_name']]['replace'] = array(
        '#type' => 'submit',
        '#value' => t('Replace all @count entries in @table', array(
          '@count' => $entry['count'],
          '@table' => $entry['table_name'],
        )),
        '#submit' => array('_database_analyser_replace_entries_submit'),
      );

      // Add the table.
      $form['output'][$entry['table_name']]['table'] = array(
        '#type' => 'markup',
        '#markup' => $entry['table'],
      );

      // Add the table class.
      $form['output'][$entry['table_name']]['replace']['#attributes']['table'] = array(
        $entry['table_name'],
      );

      // Add the column classes.
      if (!empty($entry['columns'])) {
        foreach ($entry['columns'] as $col) {
          $form['output'][$entry['table_name']]['replace']['#attributes']['columns'][] = $col;
        }
      }
    }
  }
  else {

    // Add the fieldset.
    $form['output']['empty'] = array(
      '#type' => 'markup',
      '#markup' => t('No data found.'),
    );
  }

  // Return the form.
  return $form;
}

/**
 * Create the entries table.
 *
 * @param string $search_string
 *   The search string.
 *
 * @return array
 *   Returns an array.
 *
 * @throws \Exception
 */
function _database_analyser_create_entries_table($search_string, $table = '') {

  // Get the entries.
  $entries = _database_analyser_get_entries($search_string, $table);

  // Initialize the table and header.
  $tables = array();

  $header = array(
    t('Column'),
    t('Value'),
  );

  // Check the entries.
  if (!empty($entries)) {

    // Loop through the tables.
    foreach ($entries as $table_name => $fields) {

      $columns = $rows = array();

      // Loop through the fields.
      foreach ($fields as $field => $values) {

        $columns[] = $field;

        // Loop through the values.
        foreach ($values as $i => $value) {
          $rows[] = array(
            $field,
            _database_analyser_highlight_value($value, $search_string),
          );
        }
      }

      // Create the table.
      $table = theme('table', array(
        'header' => $header,
        'rows' => $rows,
        'empty' => t('Your table is empty'),
        'sticky' => TRUE,
        'attributes' => array(
          'width' => '100%',
        ),
      ));

      $tables[] = array(
        'table_name' => $table_name,
        'count' => count($rows),
        'columns' => $columns,
        'table' => $table,
      );
    }
  }

  // Return the output.
  return $tables;
}

/**
 * Get the entries.
 *
 * @param string $search_string
 *   The search string.
 *
 * @return array
 *   Returns the entries as array.
 */
function _database_analyser_get_entries($search_string, $table = '') {

  $rows = array();

  // Get the tables.
  $tables = _database_analyser_get_tables($table);

  // Loop through the tables.
  foreach ($tables as $table => $fields) {

    // Check if the table is excluded.
    $table_excluded = _database_analyser_table_is_excluded($table);

    if (!$table_excluded) {

      // Loop through the fields.
      foreach ($fields as $field) {

        // Create the field entry.
        $entry = _database_analyser_get_table_field_entries($table, $field, $search_string);

        // Check the field entry.
        if (!empty($entry)) {

          // Add the field value.
          $rows[$table][$field] = $entry;
        }
      }
    }
  }

  // Return the database rows.
  return $rows;
}

/**
 * Get the tables in the database.
 */
function _database_analyser_get_tables($table = '') {

  // Initialize the array.
  $tables = array();

  // Get the schema.
  $schemas = drupal_get_schema();

  // Check for a single table and use that one.
  if (!empty($table)) {
    $schemas = array($table => $schemas[$table]);
  }

  // Loop through the schemas and store the fields.
  foreach ($schemas as $table => $schema) {
    if (db_table_exists($table)) {
      foreach ($schema['fields'] as $field => $values) {
        if (db_field_exists($table, $field)) {
          $tables[$table][$field] = $field;
        }
      }
    }
  }

  // Return the array.
  return $tables;
}

/**
 * Get the entries within a table.
 *
 * @param string $table
 *   The database table name.
 * @param string $field
 *   The database table field name.
 * @param string $search_string
 *   The search string.
 *
 * @return array
 *   Returns a result if found.
 */
function _database_analyser_get_table_field_entries($table, $field, $search_string) {

  // Query the table.
  $query = db_select($table, 't')
    ->fields('t', array($field))
    ->condition("t.$field", '%' . db_like($search_string) . '%', 'LIKE');

  // Fetch the col.
  return $query->execute()->fetchCol();
}

/**
 * Add highlighting in bold to a value.
 *
 * @param string $value
 *   The value to highlight in.
 * @param string $search_string
 *   The search string.
 *
 * @return mixed
 *   Returns a string.
 */
function _database_analyser_highlight_value($value, $search_string) {

  // Generate a text version.
  $value = check_plain($value);

  // Set the highlighting.
  $replace = '<strong style="color: red;">' . $search_string . '</strong>';

  // Replace the search query to surround it with strong tags.
  return str_replace($search_string, $replace, $value);
}

/**
 * Check if a table is excluded.
 *
 * @param string $table
 *   The table to check.
 *
 * @return bool
 *   Returns TRUE if excluded.
 */
function _database_analyser_table_is_excluded($table) {

  // Excluded tables.
  $excluded = array(
    'cache',
    'webform_submitted_data',
    'watchdog',
  );

  // Loop through the excluded tables.
  foreach ($excluded as $e) {

    // Match the current table.
    if (stristr($table, $e) !== FALSE) {
      return TRUE;
    }
  }

  // Return false by default.
  return FALSE;
}

/**
 * Form submit handler.
 */
function _database_analyser_submit_search($form, &$form_state) {

  // Update the default value.
  $form_state['complete_form']['input']['search']['#value'] = $form_state['input']['search'];
  $form_state['rebuild'] = TRUE;
}

/**
 * Form submit handler.
 */
function _database_analyser_replace_entries_submit($form, &$form_state) {

  // Get the triggering element.
  $triggering_element = $form_state['triggering_element'];

  // Get the search and replace values.
  $search = $form_state['input']['search'];
  $replace = $form_state['input']['replace'];
  $table = $triggering_element['#attributes']['table'][0];

  // Trigger for all columns.
  foreach ($triggering_element['#attributes']['columns'] as $column) {
    _database_analyser_replace_data($table, $column, $search, $replace);
  }
}

/**
 * Replace data in the database.
 *
 * @param string $table
 *   The table name string
 * @param string $column
 *   The column name string
 * @param string $search
 *   The search query string
 * @param string $replace
 *   The replace query string
 */
function _database_analyser_replace_data($table, $column, $search, $replace) {

  // Log the operation.
  watchdog('database_analyser', 'Updating table @table column @column from @search to @replace', array(
    '@table' => $table,
    '@column' => $column,
    '@search' => $search,
    '@replace' => $replace,
  ));

  try {

    // Run the update query.
    db_update($table)
      ->expression($column, "replace($column, :old, :new)", array(
        ':old' => $search,
        ':new' => $replace,
      ))
      ->execute();
  }
  catch (PDOException $e) {
    watchdog('database_analyser', 'PDOException: @e', array('@e' => $e->getMessage()));
  }
}
